[target.aarch64-unknown-linux-gnu]
pre-build = ["sh /project/scripts/cross-install-openssl.sh"]

[target.aarch64-unknown-linux-musl]
pre-build = ["sh /project/scripts/cross-install-openssl.sh"]

[target.x86_64-unknown-linux-gnu]
pre-build = ["sh /project/scripts/cross-install-openssl.sh"]

[target.x86_64-unknown-linux-musl]
pre-build = ["sh /project/scripts/cross-install-openssl.sh"]
