name: "Binaries (PR check)"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
            use_cross: true
            features: vendored-openssl
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04
            use_cross: true
            features: vendored-openssl
          - target: aarch64-apple-darwin
            os: macos-15
            use_cross: false
            features: vendored-openssl
          - target: aarch64-pc-windows-msvc
            os: windows-2022
            use_cross: false
            features: ""
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            use_cross: true
            features: vendored-openssl
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
            use_cross: true
            features: vendored-openssl
          - target: x86_64-apple-darwin
            os: macos-15
            use_cross: false
            features: vendored-openssl
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            use_cross: false
            features: ""
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Linux build deps
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev ca-certificates
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross
        if: matrix.use_cross == true
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
        if: endsWith(matrix.target, 'windows-msvc')
      - name: Build target
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qv
          target: ${{ matrix.target }}
          tar: none
          zip: none
          features: ${{ matrix.features }}
          token: ${{ secrets.GITHUB_TOKEN }}
