name: Build assets

on:
  push:

jobs:

  build_assets_and_add_to_release:
    needs: create_draft_release
    uses: ./.github/workflows/build_assets_and_add_to_release.yml
    with:
      app_name: "qv"
      version: "0.1"
      commitish: ${{ GITHUB_SHA }}
      tag_name: "0.1"
      add_to_release: "false"