name: Publish artifacts

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: true
      tag_name:
        type: string
        required: true
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
      COMMITTER_TOKEN:
        required: true

jobs:

  publish_container:
    name: Publish container ${{ inputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_name }}
          submodules: true
      -
        name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.app_name }}:${{ inputs.tag_name }}

  publish_crate:
    name: Publish crate ${{ inputs.tag_name }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_name }}
          submodules: true
      -
        name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
          default: true
      -
        name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish_homebrew_formula_update:
   name: Publish Homebrew formula update
   runs-on: ubuntu-latest
   steps:
     -
       name: Get version
       id: get-version
       run: echo ::set-output name=version::``$(echo ${{ inputs.tag_name }} | cut -dv -f2)``
       shell: bash
     -
       name: Update formula
       uses: mislav/bump-homebrew-formula-action@v2
       with:
         homebrew-tap: timvw/homebrew-tap
         base-branch: master
         formula-name: qv
         tag-name: ${{ inputs.tag_name }}
         download-url: ${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ inputs.tag_name }}.tar.gz
       env:
         COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}


            
