name: Published release

on:
  release:
    types: [published]

jobs:

  checkout_code_and_cleanup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Get version
        id: get-version
        run: echo "version=``$(echo ${{ github.event.release.tag_name }} | cut -dv -f2)``" >> $GITHUB_OUTPUT
        shell: bash
      -
        name: Delete release branch
        run: git push -d origin release/${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_artifacts:
    needs: checkout_code_and_cleanup
    uses: ./.github/workflows/publish_artifacts.yml
    with:
      app_name: "qv"
      tag_name: ${{ github.event.release.tag_name }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

